CREATE TABLE topic (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    dates DATETIME NOT NULL,
    status VARCHAR(50) NOT NULL,
    author VARCHAR(255) NOT NULL,
    course ENUM('JAVA', 'JAVASCRIPT', 'MYSQL', 'SOFTSKILLS', 'CSS') NOT NULL,
    CONSTRAINT unique_titulo UNIQUE (titulo(255))
);

